<a href="https://colab.research.google.com/github/sajjadgohari/Deep_Learning/blob/main/Tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf


# Different data structure => 0D, 1D, 2D, more that 2

In [3]:
a = tf.constant(5)
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
b = tf.constant([1, 2, 3])
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
c = tf.constant([[1, 2], [3, 4]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
d = tf.constant([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

# Different Opperation

In [7]:
a = tf.constant([1, 2])
b = tf.constant([3, 4])


In [8]:
# sum
c = tf.add(a, b)
c.numpy()

array([4, 6], dtype=int32)

In [9]:
# subtract
d = tf.subtract(a, b)
d.numpy()

array([-2, -2], dtype=int32)

In [10]:
# multiplication
a_1 = tf.constant([[1, 2], [3, 4]])
b_1 = tf.constant([[0, 1], [2, 3]])

In [11]:
ew = tf.multiply(a_1, b_1)
ew.numpy()

array([[ 0,  2],
       [ 6, 12]], dtype=int32)

In [12]:
mm = tf.matmul(a_1, b_1)
mm.numpy()

array([[ 4,  7],
       [ 8, 15]], dtype=int32)

In [13]:
# Division

a  = tf.constant([1, 2])
b = tf.constant([3, 0])

In [14]:
d = tf.divide(a, b)
d

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.33333333,        inf])>

In [15]:
# Broadcasting

a = tf.constant([1, 2, 3])
b = tf.constant(4) # =>[4, 4, 4]

c = a * b
c


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12], dtype=int32)>

In [16]:
a = tf.constant([1, 2, 3])
b = tf.constant(4) # =>[4, 4, 4]

c = a + b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>

## Reshape

In [17]:
a = tf.constant([1, 2, 3, 4, 5, 6])
a.shape

TensorShape([6])

In [18]:
b = tf.reshape(a, shape=(3, 2, 1))

In [19]:
b.shape

TensorShape([3, 2, 1])

In [20]:
b

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [21]:
# add dimension

a = tf.constant([1, 2, 3, 4, 5, 6])
a.shape

TensorShape([6])

In [25]:
b = tf.expand_dims(a, 1)
b.shape

TensorShape([6, 1])

In [26]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [27]:
b

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [29]:
a = tf.constant([[1,2], [3, 4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [30]:
b = tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [34]:
from numpy import float32
c = tf.sqrt(tf.cast(a, dtype=tf.float32))
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [1.7320508, 2.       ]], dtype=float32)>

## Nin, Max, Mean, STD

In [45]:
a = tf.constant([[1, 2], [3, 4.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [46]:
min = tf.reduce_min(a, axis=1)
min.numpy()

array([1., 3.], dtype=float32)

In [47]:
max = tf.reduce_max(a, axis=1)
max.numpy()

array([2., 4.], dtype=float32)

In [52]:
# numpy
import numpy as np
a = np.array([[1, 2], [3, 4.0]])
a.mean()

np.float64(2.5)

In [53]:
avg = tf.reduce_mean(a, axis=1)
avg.numpy()

array([1.5, 3.5])

In [54]:
std = tf.math.reduce_std(a, axis=1)
std.numpy()

array([0.5, 0.5])

In [57]:
sum = tf.reduce_sum(a)
sum.numpy()


np.float64(10.0)